export enum DiscoveryRelationType {
  ROOT = 'ROOT',
  SYNONYM = 'SYNONYM',
  ANTONYM = 'ANTONYM',
  PARENT = 'PARENT',
  CHILD = 'CHILD',
  RELATED = 'RELATED',
  STATE_OF = 'STATE_OF',
  CATEGORY_OF = 'CATEGORY_OF',
  LOCATION_OF = 'LOCATION_OF'
}